parameters:
#    site_utilisateurs.example.class: Site\UtilisateursBundle\Example

services:
#    site_utilisateurs.example:
#        class: %site_utilisateurs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
