index:
    path:     /
    defaults: { _controller: PagesBundle:Pages:index }
actualites:
    path:     /actualites
    defaults: { _controller: PagesBundle:Pages:actualites }
    
fiches_voyage:
    path:     /fiches_voyages
    defaults: { _controller: PagesBundle:Pages:fichesvoyages }

carnet_de_bord:
    path:     /carnet_de_bord
    defaults: { _controller: PagesBundle:Pages:carnetdebord }